### ISSUE TITLE
CIFuzz: doesn't checkout submodules in checkout_specified_commit

### ISSUE THREAD

**Issue by deymo** [google/oss-fuzz#5908]
The RepoManager will automatically clone the source git repository at `storage/$reponame` and check out the commit or pull request being tested by cifuzz there, but there's no way to specify whether it should also checkout the submodules (either `git clone --recursive` or `git submodule update --init --recursive` after the checkout).

As a workaround we can add the following step to the cifuzz workflow when using cifuzz, but it is a bit of a hack because it hardcodes the `storage/$reponame` path in the cifuzz.yml, which happens to be the path that it is used by the cifuzz action (see [here](https://github.com/google/oss-fuzz/blob/master/infra/cifuzz/continuous_integration.py#L144)).

```yaml
    - name: Checkout source
      uses: actions/checkout@v2
      id: checkout
      with:
        path: storage/REPONAME
        submodules: true
```

Doing this checkout before the build_fuzzers actions makes the RepoManager skip the clone because the [path already exists](https://github.com/google/oss-fuzz/blob/master/infra/repo_manager.py#L238). The fetch and checkout of the merge commit under test still happens, but it is a no-op because we already checked out that exact commit with the submodules at that exact revision.

I think that ideally there should be a "submodules: true" parameter to the build_fuzzers action to make RepoManager also clone the submodules. WDYT? Is there other way to get the submodules?
