### ISSUE TITLE
Build downloading breaks sometimes

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6756]
I noticed this here https://github.com/google/oss-fuzz/pull/6688#issuecomment-954741170
And mitchel noticed it [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/test-infra-fuzz/1455911271944687616)
when using these configs:
```
env:
      - name: MODE
        value: batch
      - name: REPOSITORY
        value: test-infra
      - name: PROJECT_SRC_PATH
        value: .
      - name: SANITIZER
        value: address
      - name: WORKSPACE
        value: /logs/artifacts
      - name: DOCKER_IN_DOCKER
        value: "true"
      - name: FILESTORE
        value: gsutil
      - name: CLOUD_BUCKET
        value: gs://prow-cifuzz-test/
      - name: CFL_PLATFORM
        value: prow
      - name: DOCKER_IN_DOCKER_ENABLED
        value: "true"
```
