### ISSUE TITLE
jvm fuzzing doesn't honor `fail-fast: false`

### ISSUE THREAD

**Issue by johannes-riecken** [google/oss-fuzz#7839]
I created a [minimal jvm fuzzing project](https://github.com/johannes-riecken/java-example/runs/6817999306?check_suite_focus=true). While the fuzzing happens, the step to generate a coverage report is skipped, which shouldn't happen as I set `fail-fast: false` in the project.yml. Before, I tried to generate a coverage report using a matrix of sanitizers, but that ran the coverage report generation before the fuzzing so that the report showed 0% code coverage although fuzzing happened.

**Comment by jonathanmetzman** [comment]
> I created a [minimal jvm fuzzing project](https://github.com/johannes-riecken/java-example/runs/6817999306?check_suite_focus=true). While the fuzzing happens, the step to generate a coverage report is skipped, which shouldn't happen as I set `fail-fast: false` in the project.yml. 

I don't really know if you are holding fail-fast right, I think fail-fast applies to different jobs. But you've made batch fuzzing and running coverage consecutive steps in the same job BatchFuzzing.

Also, I'm not so familiar with the Java fuzzing, but I think using a build for fuzzing and coverage as you are is nonstandard.

Before, I tried to generate a coverage report using a matrix of sanitizers, but that ran the coverage report generation before the fuzzing so that the report showed 0% code coverage although fuzzing happened.

**Comment by johannes-riecken** [comment]
Thanks for the help. When I move the report generation into a separate job, I [get a different error](https://github.com/johannes-riecken/java-example/runs/6826192057?check_suite_focus=true).

> 2022-06-10 06:43:54,711 - root - ERROR - Out directory: /github/workspace/build-out does not exist.
> 2022-06-10 06:43:54,716 - root - ERROR - Error occurred while running in workspace /github/workspace.

**Comment by jonathanmetzman** [comment]
Because you aren't building the fuzzers in a place where the coverage step has access to it. Add that step.
It would be better if you used the provided examples.

**Comment by jonathanmetzman** [comment]
This might work:
```

name: CIFuzz
on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '43 11 * * 2'
permissions: read-all
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: jvm
          sanitizer: address
      - name: Run Fuzzers (batch)
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          language: jvm
          fuzz-seconds: 300
          mode: batch
          sanitizer: address
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/johannes-riecken/java-example-storage.git
          storage-repo-branch: main # Optional. Defaults to "main"
          storage-repo-branch-coverage: gh-pages # Optional. Defaults to "gh-pages".
  Report:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
   - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: jvm
          sanitizer: coverage
    - name: Run Fuzzers (coverage)
      id: run_coverage
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        language: jvm
        fuzz-seconds: 300
        mode: coverage
        sanitizer: address
        storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/johannes-riecken/pacman-java-storage.git
        storage-repo-branch: main # Optional. Defaults to "main"
        storage-repo-branch-coverage: gh-pages # Optional. Defaults to "gh-pages".
```
