### ISSUE TITLE
Introduce target.yaml meta info file

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#89]
Example:

```yaml
target: file
homepage: "http://www.darwinsys.com/file/"
primary_contact: "my_email@email.com"
cc_emails: 
 - "my_email@email.com"
```
